In [1]:
import pandas as pd
import numpy as np
import config

In [4]:
IR = pd.read_csv(config.ROOT_DIR+'/Datasets/IR.csv', sep='\t',index_col=0)
FG = pd.read_csv(config.ROOT_DIR+'/Datasets/functional_groups.csv',index_col=0,sep='\t')
FG.dropna()

,CAS,COOH,CO,CS,imines,imides,NH2,NH1,NH0,amides,...,nitrobenzene,nitroso,methoxy,CX,epoxides,alkane,methyl,alkene,alkyne,alcohols
0,100-00-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100-01-6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100-02-7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,100043-29-6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100046-00-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28989,537-98-4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0
28990,53798-46-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,2.0,0.0,0.0,0.0
28991,5380-42-7,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
28992,538-07-8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.0,0.0,5.0,1.0,0.0,0.0,0.0
28993,538-08-9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0

In [5]:
IR

,0,1,2,3,4,5,6,7,8,9,...,11991,11992,11993,11994,11995,11996,11997,11998,11999,12000
0,709-63-7,0.063047,0.064134,0.065221,0.066308,0.067395,0.068470,0.069259,0.070049,0.070838,...,0.000536,0.000540,0.000544,0.000548,0.000552,0.000551,0.000542,0.000533,0.000523,0.000514
1,871-83-0,0.000077,0.000076,0.000076,0.000075,0.000074,0.000073,0.000072,0.000071,0.000070,...,0.000090,0.000091,0.000091,0.000091,0.000092,0.000092,0.000092,0.000093,0.000093,0.000093
2,484-66-2,0.000324,0.000323,0.000323,0.000323,0.000323,0.000323,0.000322,0.000322,0.000321,...,0.000352,0.000342,0.000332,0.000322,0.000312,0.000302,0.000292,0.000282,0.000275,0.000271
3,17075-14-8,0.024807,0.024869,0.024932,0.024994,0.025056,0.025119,0.025181,0.025243,0.025353,...,0.039108,0.039101,0.039101,0.039101,0.039101,0.039101,0.039101,0.039101,0.039101,0.039101
4,2541-75-5,0.000461,0.000462,0.000463,0.000463,0.000464,0.000464,0.000439,0.000415,0.000390,...,0.000314,0.000296,0.000278,0.000260,0.000242,0.000242,0.000276,0.000310,0.000343,0.000377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10202,84381-54-4,0.008407,0.008420,0.008432,0.008445,0.008457,0.008470,0.008485,0.008501,0.008517,...,0.000291,0.000301,0.000312,0.000322,0.000333,0.000337,0.000329,0.000321,0.000314,0.000306
10203,143-07-7,0.062326,0.062347,0.062368,0.062388,0.062409,0.062405,0.062363,0.062322,0.062281,...,0.002098,0.002036,0.001974,0.001912,0.001850,0.001894,0.002010,0.002125,0.002241,0.002357
10204,2040-04-2,0.003311,0.003263,0.003214,0.003166,0.003117,0.003069,0.003023,0.002977,0.002930,...,0.000147,0.000150,0.000152,0.000155,0.000157,0.000158,0.000157,0.000155,0.000153,0.000151
10205,102-47-6,0.006543,0.006626,0.006710,0.006794,0.006878,0.006824,0.006568,0.006312,0.006055,...,0.004697,0.004854,0.005011,0.005168,0.005325,0.005260,0.005045,0.004831,0.004616,0.004402
10206,28281-49-4,0.001774,0.001792,0.001810,0.001828,0.001846,0.001864,0.001896,0.001927,0.001959,...,0.000261,0.000258,0.000255,0.000252,0.000249,0.000249,0.000258,0.000266,0.000275,0.000284

In [26]:
new_rows = []

In [27]:
for index,row in IR.iterrows():
    try:
        CAS_id=row[0]
        #print(CAS_id)
        IR_array = row.values[1:]
        x = FG.loc[FG['CAS']==CAS_id]
        if len(x.values) == 0:
            continue
        print(index)
        FG_array = x.values[0][1:]
        new_array = np.append(IR_array,FG_array)
        
        new_rows.append(new_array.tolist())
        
    except Exception as e:
        print(e)

2
3
4
5
6
7
9
10
11
12
13
14
15
17
18
19
21
22
24
26
27
28
30
31
32
33
34
35
39
40
41
42
43
44
45
46
48
49
50
52
53
54
55
60
62
63
65
66
67
68
69
70
71
73
74
75
77
78
80
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
99
100
101
103
104
105
106
108
110
111
112
113
115
117
118
120
121
126
127
129
130
131
132
133
134
135
136
137
138
141
144
145
146
147
150
152
153
154
156
157
158
159
162
164
166
167
170
172
174
176
179
181
183
184
186
188
189
192
193
195
197
198
199
201
202
203
206
207
208
209
212
214
216
220
221
222
223
224
225
227
228
230
231
233
234
237
238
240
243
244
247
249
250
253
256
257
258
260
261
262
265
267
268
269
270
272
274
277
278
279
280
281
282
283
284
285
287
288
290
292
293
295
296
297
298
299
300
302
303
305
306
307
309
311
312
313
314
316
318
319
321
322
323
324
326
327
331
333
334
337
339
343
346
347
348
349
350
351
352
354
355
356
358
359
360
362
363
364
366
367
368
369
370
371
373
374
375
376
377
380
383
384
387
389
392
394
395
396
397
400
401
402
403
404
406
409
410
411
412
416
417
418
420
422
424
425
426
427
429
430
431
432
433
434
436
437
438
439
440
442
443
444
445
446
448
449
450
451
452
456
457
458
459
461
462
463
464
465
466
467
468
469
470
471
472
473
476
477
478
479
480
481
482
483
484
486
488
489
492
495
498
501
502
503
506
507
510
511
515
516
518
522
523
525
528
532
533
534
535
536
537
539
540
542
544
546
547
548
549
550
551
554
556
558
559
561
562
564
565
566
569
570
571
572
578
579
580
582
583
585
586
587
589
590
591
592
595
596
597
599
600
602
603
604
606
608
609
610
611
612
613
616
617
618
619
620
623
625
626
629
630
631
633
637
640
641
642
643
645
646
651
652
654
655
657
659
662
663
665
666
667
669
671
675
677
678
679
680
683
684
688
689
691
692
693
695
696
697
700
702
703
706
708
709
711
713
714
715
716
718
719
721
722
723
724
725
726
728
729
731
732
733
734
738
741
742
746
747
749
751
752
753
754
755
757
760
761
763
764
765
766
767
768
771
772
773
774
776
777
778
779
783
784
785
787
788
789
792
794
795
798
801
802
803
804
805
806
807
808
809
810
811
812
817
818
819
820
821
822
823
824
827
829
831
833
834
836
837
838
839
840
842
843
849
850
851
852
854
856
857
859
860
861
862
863
864
866
869
871
873
874
876
878
880
881
882
884
885
886
889
892
893
894
895
898
900
902
903
906
907
908
909
910
911
913
914
916
917
918
919
920
921
922
926
927
928
929
930
933
934
936
937
939
940
941
942
944
946
949
950
951
953
955
958
959
960
961
969
970
974
975
978
979
980
982
983
984
985
986
988
990
991
992
994
996
997
999
1000
1001
1002
1003
1006
1007
1008
1011
1012
1013
1014
1016
1017
1019
1020
1022
1023
1025
1028
1029
1030
1032
1033
1034
1035
1038
1039
1045
1047
1049
1053
1054
1055
1057
1058
1059
1062
1066
1069
1070
1071
1072
1075
1076
1077
1080
1081
1083
1086
1088
1089
1091
1094
1095
1097
1098
1099
1100
1102
1103
1106
1107
1109
1110
1111
1112
1113
1114
1116
1117
1119
1120
1121
1122
1123
1124
1125
1126
1128
1129
1130
1133
1135
1138
1143
1145
1146
1147
1149
1150
1151
1152
1153
1156
1157
1158
1159
1160
1161
1164
1166
1167
1169
1170
1174
1176
1178
1179
1180
1182
1184
1185
1186
1189
1190
1191
1192
1193
1194
1195
1196
1197
1200
1201
1203
1204
1205
1207
1208
1209
1210
1211
1213
1216
1217
1220
1222
1224
1227
1228
1229
1230
1231
1233
1236
1237
1238
1239
1243
1244
1245
1247
1248
1249
1250
1252
1253
1254
1255
1258
1260
1261
1262
1264
1265
1267
1268
1269
1270
1271
1274
1275
1277
1279
1281
1282
1284
1286
1287
1288
1291
1292
1294
1295
1296
1297
1298
1299
1300
1301
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1316
1317
1318
1319
1320
1324
1325
1328
1329
1330
1331
1332
1334
1335
1336
1337
1338
1341
1342
1343
1344
1345
1347
1349
1350
1352
1353
1354
1355
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1370
1371
1372
1373
1374
1375
1377
1378
1379
1380
1381
1382
1383
1385
1386
1387
1388
1390
1393
1394
1395
1397
1398
1401
1403
1405
1410
1412
1415
1416
1417
1418
1419
1421
1423
1425
1427
1428
1430
1431
1432
1433
1435
1436
1437
1438
1440
1443
1444
1445
1449
1451
1452
1453
1454
1455
1456
1458
1459
1460
1461
1466
1468
1471
1472
1474
1475
1476
1479
1480
1481
1482
1484
1485
1486
1488
1490
1493
1496
1498
1499
1500
1506
1508
1509
1510
1511
1512
1513
1514
1515
1518
1519
1521
1524
1526
1529
1531
1532
1534
1535
1536
1538
1539
1542
1543
1544
1545
1546
1547
1549
1550
1551
1552
1555
1556
1557
1559
1560
1561
1562
1563
1565
1569
1570
1572
1573
1576
1577
1578
1580
1581
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1597
1599
1600
1602
1604
1605
1607
1608
1609
1611
1612
1613
1616
1618
1619
1622
1623
1624
1625
1627
1630
1631
1634
1635
1638
1640
1645
1646
1647
1649
1650
1652
1654
1655
1656
1659
1664
1665
1668
1669
1672
1675
1676
1677
1678
1679
1682
1683
1684
1685
1687
1689
1690
1691
1692
1694
1695
1696
1699
1700
1702
1704
1705
1706
1710
1711
1712
1714
1715
1716
1717
1721
1722
1723
1725
1727
1728
1729
1730
1731
1732
1733
1734
1736
1737
1738
1739
1740
1742
1746
1747
1748
1749
1750
1751
1752
1753
1754
1756
1758
1761
1762
1763
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1777
1778
1780
1783
1786
1787
1788
1789
1791
1795
1796
1797
1803
1804
1805
1806
1809
1812
1815
1817
1819
1820
1821
1822
1823
1824
1827
1829
1830
1831
1835
1836
1837
1840
1841
1842
1845
1846
1847
1848
1851
1852
1855
1857
1858
1860
1861
1862
1865
1866
1867
1870
1871
1873
1875
1878
1879
1880
1881
1883
1884
1887
1888
1889
1890
1895
1899
1900
1901
1902
1903
1904
1905
1908
1910
1911
1915
1917
1919
1922
1925
1928
1929
1932
1933
1934
1935
1937
1939
1940
1941
1943
1944
1945
1949
1950
1951
1952
1953
1955
1957
1958
1959
1962
1966
1970
1975
1976
1977
1978
1979
1981
1984
1985
1987
1988
1990
1991
1992
1993
1994
1995
1996
2001
2002
2003
2007
2008
2009
2010
2011
2012
2013
2014
2016
2017
2019
2020
2021
2023
2024
2025
2029
2030
2031
2033
2035
2036
2039
2041
2042
2043
2044
2045
2049
2050
2051
2052
2054
2056
2058
2060
2061
2062
2063
2064
2067
2071
2072
2073
2074
2075
2077
2079
2081
2083
2084
2085
2087
2090
2092
2093
2097
2098
2099
2104
2106
2107
2108
2109
2110
2111
2112
2113
2114
2116
2118
2119
2120
2124
2125
2126
2130
2134
2135
2136
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2150
2151
2152
2153
2154
2155
2157
2158
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2173
2175
2177
2178
2180
2181
2183
2185
2186
2187
2191
2192
2194
2195
2196
2199
2200
2201
2203
2204
2206
2207
2208
2209
2211
2212
2213
2214
2215
2216
2217
2220
2222
2225
2226
2228
2230
2232
2235
2236
2237
2238
2240
2242
2243
2245
2246
2247
2248
2249
2250
2251
2252
2255
2256
2258
2261
2267
2268
2269
2273
2274
2276
2277
2279
2281
2283
2284
2286
2288
2289
2290
2291
2293
2294
2295
2298
2299
2300
2302
2303
2304
2305
2307
2308
2309
2310
2311
2313
2315
2316
2321
2322
2324
2326
2327
2329
2330
2335
2336
2339
2341
2347
2348
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2364
2365
2366
2369
2372
2373
2376
2377
2378
2380
2381
2382
2383
2384
2387
2389
2390
2391
2392
2394
2395
2396
2397
2402
2403
2404
2405
2408
2409
2411
2412
2414
2415
2417
2420
2421
2423
2424
2425
2426
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2440
2441
2442
2444
2446
2447
2448
2449
2451
2454
2455
2457
2460
2462
2463
2465
2467
2468
2470
2471
2472
2473
2474
2476
2477
2478
2479
2481
2482
2483
2484
2485
2488
2490
2492
2493
2495
2496
2498
2500
2501
2502
2503
2505
2506
2507
2508
2509
2511
2512
2513
2514
2516
2519
2521
2522
2523
2524
2526
2528
2530
2532
2534
2535
2536
2537
2538
2539
2543
2544
2547
2549
2550
2551
2553
2554
2555
2556
2558
2559
2560
2561
2564
2566
2567
2568
2569
2571
2574
2575
2576
2577
2579
2581
2582
2583
2584
2587
2588
2589
2590
2595
2596
2597
2598
2599
2600
2602
2603
2604
2605
2607
2609
2610
2611
2618
2619
2620
2621
2622
2625
2627
2628
2630
2634
2635
2636
2637
2640
2642
2643
2644
2648
2651
2652
2653
2654
2656
2657
2659
2660
2661
2662
2664
2665
2667
2670
2671
2672
2673
2674
2675
2676
2677
2678
2681
2683
2684
2689
2691
2692
2693
2695
2696
2697
2699
2700
2701
2702
2703
2706
2708
2709
2710
2711
2713
2716
2717
2718
2719
2720
2721
2722
2723
2725
2726
2728
2730
2731
2732
2733
2734
2735
2739
2740
2741
2742
2744
2747
2749
2752
2754
2756
2757
2759
2760
2765
2766
2768
2771
2772
2774
2775
2778
2779
2780
2781
2782
2785
2787
2791
2792
2793
2794
2795
2796
2798
2801
2802
2803
2804
2806
2807
2810
2813
2814
2816
2818
2819
2821
2823
2824
2825
2827
2828
2829
2830
2832
2833
2835
2837
2838
2841
2842
2843
2844
2846
2847
2848
2849
2850
2852
2853
2855
2856
2857
2862
2863
2866
2867
2868
2871
2873
2874
2876
2879

2880
2881
2882
2884
2886
2887
2889
2891
2893
2895
2896
2897
2898
2899
2901
2902
2903
2904
2905
2908
2910
2913
2914
2915
2916
2918
2919
2922
2923
2925
2926
2928
2933
2934
2935
2937
2940
2941
2942
2943
2944
2945
2949
2950
2952
2953
2954
2955
2957
2959
2960
2961
2963
2964
2965
2967
2970
2973
2975
2976
2977
2979
2980
2983
2985
2986
2988
2989
2993
2996
2998
2999
3001
3002
3003
3004
3006
3007
3008
3010
3011
3012
3013
3014
3017
3018
3019
3023
3024
3027
3028
3029
3035
3036
3037
3039
3041
3043
3044
3046
3047
3048
3052
3053
3054
3055
3056
3057
3064
3065
3066
3069
3071
3072
3073
3074
3076
3077
3078
3080
3081
3082
3083
3084
3085
3087
3089
3091
3093
3096
3097
3098
3100
3101
3102
3103
3104
3105
3106
3108
3111
3113
3116
3117
3118
3119
3121
3122
3125
3126
3127
3128
3129
3130
3132
3136
3139
3140
3142
3143
3144
3145
3146
3148
3151
3152
3154
3158
3159
3160
3161
3162
3163
3165
3166
3167
3170
3171
3172
3174
3175
3176
3177
3178
3179
3181
3182
3183
3186
3187
3188
3189
3191
3192
3193
3197
3198
3201
3202
3208
3211
3212
3213
3214
3215
3216
3217
3219
3220
3221
3223
3227
3228
3229
3230
3231
3232
3233
3237
3238
3239
3240
3242
3244
3245
3246
3247
3249
3250
3251
3252
3253
3257
3259
3263
3265
3266
3267
3268
3270
3271
3272
3273
3274
3275
3276
3277
3279
3281
3282
3283
3285
3286
3287
3288
3293
3298
3299
3300
3303
3304
3305
3306
3308
3309
3311
3313
3314
3319
3320
3321
3322
3324
3326
3328
3329
3330
3331
3334
3336
3337
3338
3339
3340
3341
3343
3345
3346
3353
3355
3356
3357
3358
3361
3362
3363
3365
3367
3369
3370
3371
3372
3374
3376
3377
3379
3381
3382
3386
3388
3391
3392
3394
3396
3400
3401
3405
3406
3407
3408
3409
3411
3412
3414
3416
3417
3421
3422
3423
3424
3426
3428
3429
3430
3431
3432
3433
3435
3437
3438
3439
3440
3441
3442
3445
3446
3449
3452
3453
3454
3456
3457
3458
3459
3460
3462
3465
3467
3468
3469
3471
3474
3477
3478
3481
3483
3485
3486
3487
3489
3490
3498
3502
3504
3505
3506
3508
3511
3513
3519
3521
3523
3527
3528
3530
3531
3532
3534
3536
3537
3539
3540
3541
3542
3543
3545
3547
3550
3551
3554
3557
3558
3561
3562
3563
3564
3565
3566
3568
3569
3570
3573
3574
3575
3576
3578
3581
3583
3589
3590
3593
3596
3597
3598
3601
3603
3604
3605
3607
3612
3613
3614
3618
3621
3622
3624
3626
3627
3630
3632
3633
3634
3636
3637
3639
3640
3641
3643
3645
3646
3647
3648
3650
3651
3655
3656
3657
3658
3660
3661
3662
3663
3664
3665
3668
3669
3672
3674
3675
3677
3678
3681
3682
3684
3685
3687
3688
3689
3691
3692
3693
3695
3701
3704
3705
3706
3707
3710
3711
3712
3713
3714
3716
3717
3720
3724
3725
3726
3727
3728
3730
3731
3732
3733
3734
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3751
3752
3753
3757
3760
3761
3762
3764
3766
3767
3768
3772
3774
3775
3777
3782
3783
3784
3786
3787
3788
3791
3792
3794
3796
3797
3798
3799
3800
3802
3803
3807
3809
3810
3811
3814
3815
3817
3818
3820
3821
3822
3823
3824
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3840
3842
3843
3846
3848
3849
3852
3853
3854
3855
3856
3858
3859
3860
3861
3862
3864
3865
3866
3867
3868
3869
3871
3873
3874
3875
3876
3883
3886
3887
3888
3889
3890
3891
3892
3893
3894
3896
3897
3898
3899
3901
3902
3903
3904
3906
3907
3910
3911
3912
3913
3914
3915
3916
3918
3919
3920
3922
3924
3926
3927
3928
3929
3930
3931
3934
3935
3937
3941
3944
3946
3947
3948
3951
3952
3953
3954
3955
3956
3958
3959
3960
3961
3962
3964
3965
3966
3967
3968
3969
3973
3974
3978
3979
3983
3984
3985
3988
3989
3990
3993
3994
3996
3997
3998
3999
4000
4002
4004
4005
4009
4010
4011
4014
4016
4018
4019
4021
4022
4024
4027
4028
4031
4033
4035
4036
4038
4039
4041
4042
4043
4044
4045
4047
4048
4050
4051
4052
4053
4055
4056
4060
4061
4063
4064
4065
4066
4067
4068
4069
4070
4071
4072
4073
4074
4075
4077
4078
4081
4082
4083
4085
4086
4087
4088
4089
4090
4091
4092
4094
4096
4098
4100
4101
4103
4107
4109
4110
4113
4114
4115
4116
4117
4119
4120
4124
4127
4128
4129
4130
4132
4133
4136
4137
4138
4139
4141
4143
4144
4145
4147
4148
4151
4152
4154
4156
4157
4158
4160
4161
4163
4164
4165
4166
4167
4169
4170
4171
4173
4174
4177
4178
4183
4184
4185
4187
4189
4190
4192
4193
4194
4195
4196
4197
4199
4200
4201
4202
4203
4204
4205
4211
4212
4214
4215
4216
4217
4219
4221
4222
4223
4224
4225
4227
4228
4230
4231
4232
4233
4234
4236
4237
4238
4239
4240
4241
4242
4243
4245
4253
4254
4255
4256
4257
4258
4259
4260
4262
4267
4268
4269
4270
4271
4272
4274
4276
4277
4278
4279
4280
4283
4284
4286
4287
4288
4289
4291
4292
4295
4296
4299
4301
4302
4303
4304
4305
4307
4310
4313
4315
4316
4318
4319
4320
4321
4322
4324
4328
4331
4335
4336
4337
4340
4341
4343
4344
4348
4350
4351
4352
4353
4355
4360
4363
4365
4366
4367
4368
4371
4375
4376
4377
4379
4380
4382
4383
4387
4389
4391
4392
4398
4400
4404
4406
4408
4412
4413
4414
4415
4417
4418
4420
4421
4423
4428
4430
4432
4433
4434
4435
4436
4437
4438
4439
4440
4442
4443
4444
4448
4450
4451
4452
4454
4456
4458
4460
4463
4466
4467
4468
4469
4470
4471
4472
4473
4482
4484
4485
4489
4490
4492
4493
4495
4496
4497
4498
4499
4500
4501
4502
4505
4507
4509
4511
4512
4513
4515
4521
4522
4526
4528
4531
4532
4535
4539
4540
4541
4542
4544
4545
4546
4547
4548
4551
4552
4553
4555
4556
4558
4562
4563
4565
4567
4570
4571
4572
4574
4576
4577
4579
4581
4586
4587
4588
4589
4590
4593
4595
4596
4598
4599
4600
4601
4603
4605
4606
4608
4609
4610
4611
4613
4614
4616
4618
4625
4626
4628
4636
4638
4639
4640
4641
4644
4645
4650
4651
4653
4656
4657
4658
4659
4660
4661
4662
4664
4666
4667
4669
4674
4675
4676
4678
4679
4681
4682
4685
4687
4691
4692
4695
4700
4701
4702
4703
4704
4705
4706
4708
4709
4711
4712
4714
4715
4716
4717
4718
4719
4721
4722
4724
4727
4730
4733
4734
4735
4738
4739
4740
4741
4743
4744
4747
4748
4749
4750
4751
4752
4755
4757
4758
4759
4760
4761
4763
4764
4765
4766
4768
4769
4770
4771
4772
4773
4774
4775
4777
4778
4780
4782
4783
4784
4785
4786
4789
4790
4791
4792
4795
4796
4797
4800
4801
4802
4804
4809
4810
4811
4812
4814
4815
4819
4820
4822
4823
4824
4825
4828
4829
4830
4831
4832
4833
4834
4836
4839
4841
4842
4844
4845
4847
4849
4850
4851
4852
4855
4856
4857
4858
4859
4860
4861
4862
4863
4864
4865
4866
4867
4868
4870
4872
4875
4876
4877
4878
4879
4880
4883
4884
4885
4889
4890
4892
4893
4894
4896
4899
4900
4901
4903
4904
4905
4906
4909
4911
4912
4913
4914
4915
4916
4917
4918
4920
4922
4923
4924
4928
4929
4930
4935
4936
4938
4939
4941
4942
4944
4946
4948
4949
4951
4953
4954
4955
4957
4958
4959
4963
4964
4965
4966
4967
4971
4972
4974
4977
4978
4979
4980
4981
4982
4985
4986
4987
4989
4991
4995
4998
5000
5001
5002
5003
5004
5005
5008
5009
5011
5012
5013
5017
5020
5021
5023
5024
5026
5027
5028
5030
5031
5034
5036
5037
5038
5040
5042
5044
5045
5046
5047
5049
5050
5051
5053
5054
5058
5059
5060
5062
5063
5064
5066
5067
5069
5070
5071
5074
5075
5076
5077
5078
5080
5081
5082
5083
5085
5087
5091
5092
5093
5096
5097
5098
5099
5102
5103
5105
5106
5107
5109
5110
5112
5117
5118
5121
5122
5123
5125
5126
5128
5129
5130
5136
5140
5141
5143
5144
5145
5149
5150
5151
5152
5153
5154
5155
5156
5157
5159
5160
5161
5162
5164
5165
5166
5174
5175
5176
5177
5178
5179
5180
5181
5182
5186
5188
5189
5191
5197
5200
5201
5202
5204
5205
5207
5208
5211
5212
5213
5219
5220
5221
5222
5223
5224
5225
5226
5229
5230
5231
5235
5236
5238
5239
5241
5242
5243
5244
5247
5251
5255
5256
5258
5259
5262
5263
5264
5266
5267
5271
5274
5275
5276
5277
5278
5279
5285
5286
5287
5288
5289
5292
5295
5296
5297
5299
5300
5301
5302
5303
5304
5305
5306
5308
5309
5314
5315
5316
5318
5319
5320
5321
5323
5324
5325
5326
5327
5328
5329
5332
5333
5334
5335
5336
5338
5339
5340
5341
5343
5346
5349
5350
5352
5354
5356
5358
5359
5363
5364
5366
5369
5370
5372
5373
5375
5377
5378
5379
5381
5382
5384
5385
5386
5388
5389
5392
5393
5398
5401
5403
5404
5405
5406
5410
5412
5413
5414
5416
5417
5418
5419
5420
5422
5424
5425
5426
5427
5428
5429
5431
5432
5433
5436
5437
5439
5440
5441
5442
5445
5446
5448
5449
5450
5452
5454
5457
5458
5459
5461
5462
5463
5465
5467
5468
5472
5473
5474
5475
5476
5477
5478
5479
5482
5483
5485
5486
5488
5489
5490
5491
5492
5495
5498
5502
5503
5506
5508
5510
5511
5512
5513
5514
5516
5517
5518
5519
5520
5521
5522
5523
5525
5526
5527
5528
5529
5530
5531
5533
5534
5535
5536
5538
5539
5541
5543
5544
5546
5547
5548
5549
5551
5552
5554
5555
5557
5560
5561
5562
5563
5564
5567
5568
5571
5572
5573
5577
5578
5579
5580
5582
5583
5585
5586
5587
5589
5590
5592
5593
5595
5596
5597
5599
5600
5605
5606
5607
5608
5609
5610
5612
5613
5616

5618
5619
5620
5623
5625
5626
5627
5630
5631
5633
5634
5636
5637
5639
5640
5642
5647
5650
5651
5652
5653
5656
5657
5658
5661
5662
5663
5665
5666
5667
5668
5669
5670
5672
5673
5674
5675
5676
5678
5679
5680
5681
5682
5683
5686
5689
5690
5691
5693
5695
5696
5699
5700
5701
5704
5706
5707
5709
5710
5714
5715
5716
5717
5719
5721
5723
5728
5729
5730
5731
5732
5733
5735
5736
5738
5741
5744
5746
5748
5750
5751
5752
5754
5756
5758
5759
5760
5761
5763
5764
5766
5768
5771
5772
5773
5774
5777
5778
5779
5780
5782
5783
5784
5785
5786
5787
5789
5791
5792
5793
5794
5795
5796
5798
5799
5802
5803
5807
5808
5812
5813
5815
5816
5817
5818
5819
5821
5822
5823
5824
5826
5827
5828
5829
5830
5832
5836
5837
5838
5839
5841
5843
5847
5848
5849
5850
5851
5852
5853
5856
5857
5858
5862
5864
5865
5866
5868
5869
5870
5872
5874
5875
5876
5878
5882
5884
5887
5889
5890
5891
5893
5894
5895
5896
5897
5899
5901
5902
5905
5907
5908
5909
5910
5911
5914
5916
5917
5918
5919
5920
5921
5923
5924
5926
5929
5933
5934
5935
5936
5937
5939
5940
5941
5942
5947
5948
5949
5952
5953
5956
5957
5961
5962
5965
5966
5967
5968
5969
5972
5973
5974
5975
5982
5983
5984
5985
5986
5988
5989
5990
5991
5992
5994
5995
5996
5998
5999
6000
6001
6002
6003
6004
6005
6008
6011
6012
6013
6014
6015
6017
6018
6019
6022
6026
6027
6028
6030
6032
6036
6038
6039
6041
6042
6044
6045
6046
6048
6051
6052
6053
6054
6055
6058
6060
6061
6062
6063
6064
6065
6068
6070
6072
6074
6078
6079
6080
6082
6083
6084
6086
6087
6088
6089
6090
6091
6092
6093
6095
6096
6099
6100
6102
6104
6106
6108
6111
6114
6121
6123
6124
6125
6127
6128
6130
6131
6132
6136
6137
6138
6139
6141
6142
6144
6145
6146
6148
6149
6150
6151
6153
6154
6156
6158
6159
6161
6162
6163
6164
6165
6166
6167
6170
6172
6173
6175
6177
6178
6179
6180
6181
6182
6183
6184
6186
6187
6188
6190
6191
6192
6195
6196
6198
6205
6206
6209
6210
6211
6212
6213
6214
6215
6217
6218
6219
6220
6225
6227
6229
6230
6232
6233
6235
6236
6238
6241
6242
6243
6244
6245
6248
6249
6250
6252
6253
6254
6255
6257
6259
6261
6264
6265
6266
6268
6269
6271
6272
6273
6274
6278
6279
6281
6283
6287
6289
6290
6291
6292
6294
6296
6297
6298
6299
6301
6304
6306
6307
6308
6309
6310
6313
6314
6319
6320
6321
6323
6325
6326
6327
6328
6330
6331
6333
6334
6335
6336
6337
6340
6341
6344
6345
6346
6347
6348
6350
6351
6352
6353
6356
6357
6358
6359
6360
6361
6362
6363
6365
6366
6367
6368
6369
6370
6371
6373
6376
6378
6382
6383
6386
6387
6389
6390
6391
6392
6394
6395
6397
6398
6400
6401
6404
6406
6408
6409
6411
6413
6414
6415
6417
6418
6419
6420
6421
6422
6423
6425
6426
6428
6431
6434
6436
6437
6438
6441
6442
6443
6445
6447
6448
6451
6454
6455
6456
6457
6459
6460
6461
6462
6463
6464
6466
6468
6471
6472
6473
6475
6477
6478
6480
6481
6483
6484
6486
6487
6489
6490
6491
6492
6494
6495
6496
6498
6499
6502
6504
6506
6508
6509
6510
6512
6513
6514
6516
6517
6521
6522
6523
6524
6527
6532
6533
6537
6539
6540
6541
6542
6543
6545
6546
6547
6549
6550
6556
6557
6558
6560
6563
6564
6565
6566
6567
6568
6571
6572
6574
6575
6576
6577
6578
6580
6581
6582
6583
6585
6586
6588
6589
6590
6592
6596
6597
6601
6603
6604
6607
6612
6614
6616
6618
6622
6623
6624
6626
6629
6630
6631
6633
6634
6636
6637
6639
6641
6645
6646
6647
6650
6651
6655
6657
6658
6659
6660
6661
6668
6670
6671
6673
6675
6676
6678
6679
6681
6683
6684
6685
6689
6691
6692
6695
6696
6699
6700
6701
6703
6705
6706
6707
6708
6709
6711
6712
6713
6716
6717
6720
6721
6722
6723
6724
6725
6726
6727
6729
6730
6731
6732
6733
6735
6736
6738
6739
6740
6743
6745
6746
6747
6748
6749
6750
6752
6753
6756
6757
6758
6759
6762
6764
6765
6768
6770
6773
6774
6775
6777
6778
6779
6781
6783
6784
6786
6788
6789
6790
6791
6793
6794
6796
6799
6801
6802
6804
6805
6806
6808
6809
6810
6811
6812
6813
6814
6815
6816
6817
6818
6819
6820
6821
6823
6824
6827
6829
6830
6831
6833
6836
6837
6838
6839
6841
6843
6845
6846
6847
6848
6850
6852
6853
6854
6855
6856
6857
6861
6863
6864
6865
6866
6870
6872
6874
6878
6879
6880
6885
6887
6888
6889
6891
6893
6895
6896
6897
6898
6899
6900
6901
6902
6903
6904
6908
6909
6911
6914
6915
6916
6919
6920
6921
6922
6924
6925
6928
6929
6930
6932
6935
6936
6937
6938
6939
6940
6941
6942
6944
6946
6950
6951
6953
6954
6955
6959
6962
6963
6964
6966
6967
6969
6970
6971
6972
6974
6975
6977
6979
6981
6982
6983
6984
6986
6987
6988
6990
6991
6992
6993
6994
6999
7000
7002
7003
7005
7007
7010
7011
7012
7013
7014
7017
7020
7021
7023
7024
7025
7026
7027
7028
7029
7030
7031
7032
7034
7036
7038
7039
7041
7042
7044
7047
7049
7051
7054
7055
7058
7060
7062
7063
7066
7067
7068
7069
7070
7071
7075
7078
7080
7081
7082
7083
7085
7087
7089
7090
7091
7092
7093
7094
7095
7097
7098
7099
7100
7101
7103
7104
7106
7108
7109
7115
7116
7118
7120
7121
7122
7123
7124
7127
7131
7132
7133
7134
7136
7137
7140
7141
7144
7145
7149
7150
7151
7152
7153
7154
7155
7156
7159
7160
7161
7164
7165
7166
7167
7172
7176
7177
7178
7179
7180
7182
7184
7185
7186
7187
7188
7191
7193
7194
7195
7197
7198
7200
7201
7204
7205
7206
7208
7210
7211
7214
7217
7219
7221
7223
7224
7226
7228
7233
7234
7235
7236
7237
7239
7240
7242
7243
7244
7248
7249
7250
7252
7253
7254
7257
7261
7263
7264
7265
7266
7267
7268
7272
7273
7274
7276
7278
7279
7280
7282
7283
7286
7287
7288
7290
7291
7292
7293
7294
7295
7296
7297
7298
7300
7301
7302
7303
7304
7307
7308
7309
7310
7315
7318
7324
7325
7326
7327
7328
7330
7335
7336
7339
7340
7342
7343
7345
7347
7348
7352
7354
7355
7356
7358
7359
7362
7364
7365
7366
7367
7370
7373
7376
7377
7379
7380
7381
7382
7391
7392
7394
7395
7398
7402
7403
7405
7408
7410
7412
7413
7415
7416
7417
7418
7419
7424
7426
7430
7431
7432
7434
7435
7438
7439
7441
7443
7444
7445
7446
7447
7448
7449
7451
7452
7453
7454
7455
7456
7457
7458
7459
7460
7461
7462
7463
7465
7466
7468
7469
7470
7471
7472
7473
7474
7475
7476
7477
7479
7480
7483
7485
7487
7488
7490
7492
7493
7494
7496
7497
7498
7499
7500
7503
7504
7509
7511
7512
7513
7514
7515
7516
7517
7519
7523
7526
7531
7532
7534
7536
7537
7539
7541
7542
7543
7544
7545
7551
7552
7556
7557
7558
7559
7561
7562
7563
7565
7566
7567
7569
7571
7572
7573
7574
7575
7578
7579
7581
7582
7583
7584
7585
7587
7590
7591
7595
7596
7597
7598
7599
7601
7603
7604
7605
7606
7607
7608
7612
7614
7615
7617
7618
7619
7620
7622
7623
7624
7627
7631
7634
7635
7636
7640
7641
7643
7644
7645
7646
7648
7649
7650
7653
7654
7655
7657
7658
7659
7660
7661
7662
7663
7664
7666
7670
7672
7673
7675
7677
7680
7684
7687
7688
7689
7691
7692
7695
7696
7697
7699
7701
7704
7705
7706
7708
7709
7710
7711
7714
7717
7718
7719
7720
7721
7722
7726
7728
7730
7731
7732
7733
7734
7735
7736
7737
7740
7741
7744
7747
7749
7753
7754
7755
7757
7759
7760
7761
7762
7763
7765
7766
7767
7768
7771
7772
7775
7777
7779
7781
7782
7783
7784
7785
7788
7790
7793
7794
7795
7798
7799
7800
7803
7804
7805
7808
7811
7814
7815
7820
7821
7822
7824
7825
7829
7830
7832
7833
7834
7836
7837
7838
7839
7842
7843
7844
7845
7846
7849
7850
7851
7857
7860
7861
7863
7866
7867
7868
7869
7872
7874
7876
7877
7878
7881
7882
7883
7886
7887
7890
7894
7895
7896
7897
7898
7899
7900
7902
7904
7905
7906
7910
7911
7912
7913
7914
7916
7918
7920
7923
7924
7925
7926
7927
7928
7929
7932
7934
7937
7939
7940
7941
7942
7944
7945
7947
7950
7951
7952
7953
7955
7956
7958
7960
7961
7962
7963
7964
7965
7966
7968
7970
7971
7972
7973
7975
7977
7978
7979
7981
7985
7989
7990
7991
7992
7995
7996
7997
7998
8000
8001
8002
8004
8006
8007
8008
8014
8015
8016
8017
8018
8019
8020
8021
8022
8023
8024
8027
8028
8029
8031
8032
8033
8034
8035
8036
8037
8038
8040
8044
8046
8049
8051
8052
8053
8055
8056
8057
8059
8061
8062
8063
8065
8066
8067
8068
8070
8073
8075
8076
8077
8081
8082
8083
8086
8088
8089
8091
8095
8096
8097
8098
8101
8106
8107
8108
8109
8110
8114
8117
8118
8119
8120
8121
8122
8124
8128
8130
8132
8135
8137
8138
8139
8140
8142
8145
8146
8147
8148
8149
8150
8152
8153
8155
8156
8157
8158
8165
8167
8170
8172
8173
8174
8175
8178
8179
8181
8182
8183
8184
8185
8186
8187
8188
8190
8191
8197
8199
8201
8203
8205
8208
8209
8211
8212
8213
8215
8216
8217
8221
8223
8224
8226
8228
8229
8230
8231
8232
8234
8237
8238
8239
8241
8242
8245
8246
8247
8250
8251
8253
8255
8258
8259
8260
8261
8263
8266
8267
8268
8269
8271
8272
8274
8276
8278
8280
8281
8282
8285
8287
8288
8289
8291
8292
8293
8295
8296
8297
8300
8301
8302
8304
8308
8309
8311
8313
8315
8317
8319
8320
8325
8327
8328
8332
8333
8334
8336
8338
8339
8341
8342

8345
8346
8347
8348
8349
8351
8352
8354
8355
8356
8362
8364
8369
8370
8371
8372
8373
8374
8375
8377
8379
8380
8381
8382
8384
8385
8387
8389
8394
8395
8397
8398
8400
8401
8403
8404
8406
8407
8408
8409
8410
8411
8412
8413
8414
8415
8416
8417
8418
8419
8420
8421
8422
8423
8424
8425
8426
8428
8429
8430
8431
8432
8434
8435
8436
8437
8441
8442
8444
8445
8446
8447
8449
8452
8453
8454
8455
8456
8458
8461
8463
8464
8465
8466
8467
8468
8469
8470
8472
8473
8475
8476
8477
8479
8480
8481
8482
8484
8486
8487
8490
8491
8492
8493
8495
8496
8502
8503
8505
8508
8509
8510
8513
8514
8515
8516
8518
8520
8521
8522
8524
8526
8529
8531
8532
8534
8535
8536
8537
8538
8540
8541
8542
8544
8546
8548
8549
8551
8552
8554
8556
8557
8558
8560
8561
8562
8563
8564
8565
8566
8568
8571
8573
8578
8580
8581
8583
8585
8589
8592
8593
8595
8598
8599
8600
8601
8603
8605
8608
8609
8610
8611
8612
8613
8614
8615
8617
8618
8620
8621
8622
8625
8629
8630
8631
8632
8636
8637
8639
8640
8641
8644
8645
8646
8651
8652
8653
8655
8656
8657
8659
8661
8662
8664
8668
8669
8670
8673
8675
8676
8677
8678
8679
8680
8681
8685
8686
8687
8689
8690
8691
8692
8693
8696
8698
8701
8703
8704
8709
8712
8713
8714
8717
8718
8720
8723
8724
8725
8726
8727
8728
8729
8730
8731
8732
8733
8737
8738
8739
8740
8741
8742
8744
8745
8748
8749
8750
8751
8752
8753
8754
8756
8759
8760
8761
8763
8764
8766
8767
8770
8772
8774
8775
8776
8777
8778
8781
8782
8783
8786
8788
8790
8791
8792
8793
8797
8799
8801
8802
8805
8806
8808
8811
8812
8814
8815
8816
8818
8820
8821
8824
8825
8826
8828
8830
8831
8833
8835
8836
8837
8839
8840
8841
8842
8843
8844
8845
8848
8852
8853
8855
8857
8858
8859
8860
8864
8865
8866
8868
8869
8870
8871
8872
8873
8874
8875
8876
8878
8879
8881
8884
8885
8886
8891
8893
8894
8895
8896
8897
8900
8902
8904
8905
8906
8907
8908
8910
8911
8913
8914
8916
8917
8918
8919
8920
8922
8924
8925
8929
8930
8931
8935
8936
8941
8943
8944
8945
8946
8947
8948
8949
8950
8951
8952
8953
8954
8956
8957
8958
8959
8961
8963
8964
8965
8969
8970
8972
8973
8976
8977
8978
8979
8980
8981
8982
8983
8984
8985
8986
8987
8988
8989
8990
8991
8992
8993
8994
8995
8999
9000
9002
9004
9005
9006
9007
9008
9009
9011
9012
9013
9014
9015
9016
9017
9020
9024
9025
9027
9029
9031
9033
9034
9038
9039
9040
9042
9043
9044
9045
9047
9049
9050
9053
9054
9055
9057
9059
9061
9062
9063
9064
9065
9067
9069
9074
9076
9077
9078
9080
9082
9085
9088
9089
9090
9091
9092
9093
9095
9096
9098
9099
9101
9102
9103
9104
9105
9106
9108
9110
9111
9112
9113
9116
9117
9118
9119
9120
9121
9122
9125
9126
9127
9128
9129
9130
9131
9132
9134
9135
9136
9138
9139
9142
9144
9145
9147
9148
9149
9150
9152
9154
9155
9156
9157
9158
9159
9160
9162
9163
9164
9165
9166
9167
9168
9169
9170
9171
9173
9174
9175
9176
9177
9178
9179
9182
9185
9186
9187
9188
9189
9191
9195
9196
9197
9198
9200
9201
9203
9205
9206
9207
9211
9212
9213
9215
9217
9220
9221
9222
9224
9226
9227
9231
9232
9234
9235
9237
9238
9243
9244
9246
9247
9248
9249
9251
9253
9254
9255
9258
9259
9260
9261
9266
9267
9270
9271
9273
9274
9276
9277
9278
9279
9280
9281
9282
9283
9284
9286
9287
9289
9290
9294
9296
9299
9302
9309
9310
9312
9314
9315
9316
9317
9318
9322
9324
9325
9326
9327
9332
9333
9336
9337
9338
9339
9341
9342
9343
9344
9345
9346
9347
9349
9350
9351
9353
9354
9355
9356
9357
9358
9359
9360
9362
9363
9365
9366
9367
9369
9370
9371
9372
9373
9374
9375
9376
9377
9379
9380
9381
9382
9384
9386
9387
9388
9390
9391
9392
9393
9395
9396
9397
9398
9399
9401
9404
9406
9408
9409
9410
9412
9414
9415
9416
9418
9419
9420
9421
9424
9425
9429
9431
9432
9434
9435
9436
9437
9438
9440
9442
9444
9446
9448
9451
9453
9454
9456
9460
9461
9462
9463
9466
9467
9468
9470
9472
9474
9475
9476
9478
9480
9481
9482
9483
9485
9491
9492
9494
9495
9496
9499
9502
9503
9506
9507
9509
9511
9513
9514
9515
9517
9518
9519
9524
9525
9528
9529
9531
9532
9534
9537
9538
9540
9543
9544
9545
9546
9547
9548
9549
9556
9557
9559
9562
9563
9565
9569
9571
9573
9574
9575
9577
9579
9580
9581
9582
9585
9587
9588
9589
9593
9594
9595
9600
9601
9602
9603
9605
9606
9607
9608
9609
9610
9611
9612
9615
9616
9617
9618
9619
9622
9624
9626
9628
9631
9632
9633
9634
9636
9637
9638
9639
9640
9641
9646
9648
9650
9651
9652
9655
9656
9657
9658
9662
9665
9666
9667
9668
9669
9672
9673
9674
9675
9677
9678
9679
9680
9682
9683
9684
9685
9686
9687
9688
9692
9693
9697
9698
9699
9700
9703
9707
9709
9711
9713
9714
9715
9719
9723
9725
9726
9730
9733
9734
9736
9737
9740
9744
9746
9747
9751
9752
9753
9754
9755
9756
9759
9760
9761
9762
9763
9764
9765
9766
9767
9768
9771
9775
9776
9777
9779
9780
9781
9782
9783
9786
9787
9789
9790
9791
9792
9793
9796
9800
9805
9806
9808
9809
9811
9812
9813
9815
9816
9819
9820
9821
9822
9825
9827
9829
9832
9833
9834
9835
9836
9839
9842
9843
9844
9845
9848
9849
9851
9852
9857
9859
9862
9868
9869
9872
9873
9874
9875
9877
9879
9880
9882
9884
9887
9888
9889
9890
9893
9896
9897
9898
9899
9901
9903
9906
9910
9913
9914
9915
9917
9918
9919
9923
9927
9928
9929
9931
9932
9934
9940
9941
9942
9945
9946
9948
9949
9951
9952
9953
9954
9957
9959
9960
9963
9964
9965
9966
9967
9970
9971
9973
9975
9977
9978
9979
9981
9982
9985
9986
9987
9988
9990
9991
9992
9993
9994
9996
9997
9998
10000
10002
10003
10004
10005
10006
10007
10008
10011
10012
10013
10014
10015
10016
10017
10018
10020
10021
10022
10023
10028
10033
10034
10035
10036
10038
10039
10041
10042
10045
10048
10049
10050
10051
10052
10055
10056
10057
10059
10064
10066
10067
10068
10071
10073
10075
10076
10078
10079
10080
10081
10082
10083
10084
10086
10089
10091
10092
10093
10095
10096
10098
10099
10101
10102
10103
10105
10107
10108
10109
10111
10113
10115
10118
10119
10120
10121
10122
10123
10125
10128
10129
10130
10131
10132
10133
10135
10137
10138
10140
10144
10145
10146
10147
10148
10153
10160
10161
10162
10164
10165
10166
10167
10168
10169
10170
10175
10176
10178
10179
10180
10181
10182
10183
10184
10185
10188
10191
10195
10196
10197
10198
10199
10201
10203
10204
10205
10206

In [28]:
print(len(new_rows))

6281

In [29]:
IR_FG = pd.DataFrame(new_rows)

In [30]:
IR_FG

,0,1,2,3,4,5,6,7,8,9,...,12021,12022,12023,12024,12025,12026,12027,12028,12029,12030
0,0.000324,0.000323,0.000323,0.000323,0.000323,0.000323,0.000322,0.000322,0.000321,0.000320,...,0.0,0.0,0.0,0.0,0.0,1.0,5.0,0.0,0.0,1.0
1,0.024807,0.024869,0.024932,0.024994,0.025056,0.025119,0.025181,0.025243,0.025353,0.025477,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.000461,0.000462,0.000463,0.000463,0.000464,0.000464,0.000439,0.000415,0.000390,0.000365,...,0.0,0.0,0.0,0.0,0.0,15.0,2.0,0.0,0.0,1.0
3,0.000103,0.000099,0.000096,0.000092,0.000088,0.000085,0.000081,0.000077,0.000074,0.000070,...,0.0,0.0,0.0,0.0,0.0,17.0,2.0,0.0,0.0,1.0
4,0.005597,0.005573,0.005549,0.005525,0.005501,0.005509,0.005565,0.005622,0.005678,0.005735,...,0.0,0.0,0.0,0.0,0.0,7.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6276,0.019872,0.019960,0.020049,0.020137,0.020226,0.020383,0.020642,0.020901,0.021160,0.021419,...,0.0,0.0,2.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0
6277,0.062326,0.062347,0.062368,0.062388,0.062409,0.062405,0.062363,0.062322,0.062281,0.062239,...,0.0,0.0,0.0,0.0,0.0,10.0,1.0,0.0,0.0,1.0
6278,0.003311,0.003263,0.003214,0.003166,0.003117,0.003069,0.003023,0.002977,0.002930,0.002884,...,0.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
6279,0.006543,0.006626,0.006710,0.006794,0.006878,0.006824,0.006568,0.006312,0.006055,0.005799,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
6280,0.001774,0.001792,0.001810,0.001828,0.001846,0.001864,0.001896,0.001927,0.001959,0.001991,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0

In [31]:
IR_FG.to_csv(config.ROOT_DIR+'/Datasets/IR-FG.csv',sep='\t')