In [1]:
import pandas as pd
import config

In [2]:
#Smiles csv file
SMILES_path = config.ROOT_DIR+'/Datasets/SMILES.csv'

#Import SMILES file
data = pd.read_csv(SMILES_path,index_col=0,sep='\t')

In [3]:
data

               CAS                                            CSMILES
0         100-00-5                        C1=CC(=CC=C1[N+](=O)[O-])Cl
1         100-01-6                         C1=CC(=CC=C1N)[N+](=O)[O-]
2         100-02-7                         C1=CC(=CC=C1[N+](=O)[O-])O
3      100043-29-6                                          C1=NNN=N1
4      100046-00-2  CC1=CC(=C(C(=C1)C)[N+](=[N+](C2=C(C=C(C=C2C)C)...
...            ...                                                ...
44450      99-98-9                                CN(C)C1=CC=C(C=C1)N
44451    9998-90-7  CC(=O)OCC([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]
44452      99-99-0                         CC1=CC=C(C=C1)[N+](=O)[O-]
44453     999-90-6                                    CC(=O)SC(C)(C)C
44454     999-97-3                            C[Si](C)(C)N[Si](C)(C)C

[44455 rows x 2 columns]

In [4]:
from rdkit import Chem
import numpy as np

In [5]:
from rdkit.Chem import Fragments

func_grp_smarts = {'alkane':'[CX4;H0,H1,H2,H4]','methyl':'[CH3]','alkene':'[CX3]=[CX3]','alkyne':'[CX2]#C',
                   'alcohols':'[#6][OX2H]'}

groups = []

for index,row in data.iterrows():
    SMILES = row[1]

    try:
        mol = Chem.MolFromSmiles(SMILES)

        #Maybe put the stuff below into a function
        
        #Substructure search for the functional groups
        
        '''Essential functional groups''' #missing alcohols
        #Many of these are redundant. For example, any imide will also have a tertiary amine
        
        COOH = Fragments.fr_COO(mol) #Carboxylic acid
        CO = Fragments.fr_C_O(mol) #Carbonyls
        CS = Fragments.fr_C_S(mol) #Thiocarbonyls
        Imines = Fragments.fr_Imine(mol) #Imines
        Imides = Fragments.fr_imide(mol) #number of imides
        NH2 = Fragments.fr_NH2(mol) #Primary amines
        NH1 = Fragments.fr_NH1(mol) #Secondary amines
        NH0 = Fragments.fr_NH0(mol) #Tertiary amines
        amides = Fragments.fr_amide(mol) #number of amides
        SH = Fragments.fr_SH(mol) #Thiol groups
        Aldehydes = Fragments.fr_aldehyde(mol) #Aldehydes
        azide = Fragments.fr_azide(mol) #number of azides
        azo = Fragments.fr_azo(mol) #number of azo groups
        phenol = Fragments.fr_phenol(mol) #number of phenols
        benzene = Fragments.fr_benzene(mol) #number of benzenes
        ester = Fragments.fr_ester(mol) #number of esters
        ether = Fragments.fr_ether(mol) #number of ethers
        urea = Fragments.fr_urea(mol) #number of urea groups
        ketones = Fragments.fr_ketone(mol) #number of ketones
        nitrile = Fragments.fr_nitrile(mol) #number of nitrile groups
        nitro = Fragments.fr_nitro(mol) #number of nitro groups
        nitrobenzene = Fragments.fr_nitro_arom(mol) #number of nitrobenzenes
        nitroso = Fragments.fr_nitroso(mol) #number of nitroso groups
        methyoxy = Fragments.fr_methoxy(mol) #number of methoxy groups
        CX = Fragments.fr_alkyl_halide(mol) #number of alkyl halides
        epoxides = Fragments.fr_epoxide(mol) #number of epoxides
        
        extragroups = []
        '''Functional groups not found by RDkit natively'''
        for f in func_grp_smarts.items():
            #print(f[1])
            extragroups.append(len(mol.GetSubstructMatches(Chem.MolFromSmarts(func_grp_smarts[f[0]]))))
        
        '''Generally more complex functional groups'''
        #Omitted from the dataset for preliminary training
        '''
        halogens = Fragments.fr_halogen(mol) #number of halogens
        Pyrroles = Fragments.fr_Nhpyrrole #number of pyrroles
        Alkyl_Carbamate = Fragments.fr_alkyl_carbamate(mol) #number of alkyl carbamates
        amidine = Fragments.fr_amidine(mol) #number of amidines
        aniline = Fragments.fr_aniline(mol) #number of anilines
        barbituates = Fragments.fr_barbitur(mol) #number of barbituate groups
        furan = Fragments.fr_furan(mol) #number of furans
        guanidine = Fragments.fr_guanido(mol) #number of guanidines
        hydrazine = Fragments.fr_hdrzine(mol) #number of hydrazines
        imidazole = Fragments.fr_imidazole(mol) #number of imidazole
        isocyan = Fragments.fr_isocyan(mol) #number of isocyanates
        isothiocyan = Fragments.fr_isothiocyan(mol) #number of isothiocyanates
        betalactam = Fragments.fr_lactam(mol) #number of beta lactams
        lactone = Fragments.fr_lactone(mol) #number of lactones
        morpholine = Fragments.fr_morpholine(mol) #number of morpholine groups
        oxazole = Fragments.fr_oxazole(mol) #number of oxazole rings
        oxime = Fragments.fr_oxime(mol) #number of oxime groups
        pAcid = Fragments.fr_phos_acid(mol) #number of phosphoric acid groups
        pEster = Fragments.fr_phos_ester(mol) #number of phosphoric ester groups
        piperzine = Fragments.fr_piperzine(mol) #number of piperzine rings        
        piperdine = Fragments.fr_piperdine(mol) #number of piperdine rings
        prisulfonamid = Fragments.fr_prisulfonamd(mol) #number of primary sulfonamides
        pyridine = Fragments.fr_pyridine(mol) #number of pyridines
        thioether = Fragments.fr_sulfide(mol) #Number of thioethers
        sulfonamides = Fragments.fr_sulfonamd(mol) #number of sulfonamide groups
        sulfone = Fragments.fr_sulfone(mol) #number of sulfone groups
        tetrazole = Fragments.fr_tetrazole(mol) #number of tetrazole rings
        thiazole = Fragments.fr_thiazole(mol) #Number of thiazole rings
        thiocyanates = Fragments.fr_thiocyan(mol) #number of thiocyanates
        thiophene = Fragments.fr_thiophene(mol) #number of thiophenes'''
        
        func_groups_common = [COOH,CO,CS,Imines,Imides,NH2,
                              NH1,NH0,amides,SH,Aldehydes,azide,
                              azo,phenol,benzene,ester,ether,urea,
                              ketones,nitrile,nitro,nitrobenzene,nitroso,methyoxy,
                              CX,epoxides]
        
        '''[COOH,CO,CS,Imines,Imides,NH2,
            NH1,NH0,amides,SH,Aldehydes,azide,
            azo,phenol,benzene,ester,ether,urea,
            ketones,nitrile,nitro,nitrobenzene,nitroso,methyoxy,
            CX,epoxides,alkane,methyl,alkene,alkyne,alcohols]'''

        datarow = [row[0]]+func_groups_common + extragroups
        groups.append(datarow)
        #print(SMILES,str(func_groups_common))
        
    except Exception as e:
        groups.append([np.NaN]*32)
        continue

[15:29:12] WARNING: not removing hydrogen atom without neighbors
[15:29:13] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:15] WARNING: not removing hydrogen atom without neighbors
[15:29:16] WARNING: not removing hydrogen atom without neighbors
[15:29:16] WARNING: not removing hydrogen atom without neighbors
[15:29:16] WARNING: not removing hydrogen atom without neighbors
[15:29:16] WARNING: not removing hydrogen atom without neighbors
[15:29:16] WARNING: not removing hydrogen atom without neighbors
[15:29:16] WARNING: not removing hydrogen atom without neighbors
[15:29:17] WARNING: not removing hydrogen atom without neighbors
[15:29:17] WARNING: not removing hydrogen atom without neighbors
[15:29:17] WARNING: not removing hydrogen atom without neighbors
[15:29:17] Explicit valence for atom # 1 Cl, 5, is greater than permitted
[15:29:17] Explicit valence for atom # 1 Cl, 5, is greater than permitted
[15:29:17] WARNING: not removing hydrogen atom without neighbors
[15:29:17] WARNING: not removing hydrogen atom without neighbors
[15:29:17] Explicit valence for atom # 1 Cl, 6, is greater than permitted
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:18] WARNING: not removing hydrogen atom without neighbors
[15:29:19] Explicit valence for atom # 1 Cl, 2, is greater than permitted
[15:29:19] Explicit valence for atom # 0 Cl, 2, is greater than permitted
[15:29:19] Explicit valence for atom # 0 Cl, 2, is greater than permitted
[15:29:19] Explicit valence for atom # 0 Cl, 2, is greater than permitted
[15:29:19] WARNING: not removing hydrogen atom without neighbors
[15:29:19] WARNING: not removing hydrogen atom without neighbors
[15:29:19] WARNING: not removing hydrogen atom without neighbors
[15:29:19] WARNING: not removing hydrogen atom without neighbors
[15:29:19] WARNING: not removing hydrogen atom without neighbors
[15:29:20] WARNING: not removing hydrogen atom without neighbors
[15:29:20] WARNING: not removing hydrogen atom without neighbors
[15:29:20] WARNING: not removing hydrogen atom without neighbors
[15:29:20] WARNING: not removing hydrogen atom without neighbors
[15:29:20] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[15:29:20] Explicit valence for atom # 1 I, 7, is greater than permitted
[15:29:20] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[15:29:22] WARNING: not removing hydrogen atom without neighbors
[15:29:23] Explicit valence for atom # 1 Cl, 2, is greater than permitted
[15:29:26] Explicit valence for atom # 1 Cl, 3, is greater than permitted
[15:29:26] WARNING: not removing hydrogen atom without neighbors
[15:29:27] WARNING: not removing hydrogen atom without neighbors
[15:29:27] WARNING: not removing hydrogen atom without neighbors
[15:29:27] WARNING: not removing hydrogen atom without neighbors
[15:29:30] WARNING: not removing hydrogen atom without neighbors
[15:29:36] WARNING: not removing hydrogen atom without neighbors
[15:29:36] Explicit valence for atom # 1 Cl, 7, is greater than permitted
[15:29:36] WARNING: not removing hydrogen atom without neighbors
[15:29:36] WARNING: not removing hydrogen atom without neighbors
[15:29:36] WARNING: not removing hydrogen atom without neighbors
[15:29:36] WARNING: not removing hydrogen atom without neighbors
[15:29:36] WARNING: not removing hydrogen atom without neighbors
[15:29:36] Explicit valence for atom # 1 Br, 3, is greater than permitted
[15:29:36] Explicit valence for atom # 1 Br, 5, is greater than permitted
[15:29:36] Explicit valence for atom # 1 Cl, 3, is greater than permitted

In [6]:
print(len(groups[0]))
GroupData = pd.DataFrame(groups,columns=['CAS','COOH','CO','CS','imines','imides','NH2','NH1','NH0','amides','SH','aldehyde','azide','azo','phenol','benzene','ester','ether','urea','ketones','nitrile','nitro','nitrobenzene','nitroso','methoxy','CX','epoxides','alkane','methyl','alkene','alkyne','alcohols'])

32

In [7]:
GroupData

,CAS,COOH,CO,CS,imines,imides,NH2,NH1,NH0,amides,...,nitrobenzene,nitroso,methoxy,CX,epoxides,alkane,methyl,alkene,alkyne,alcohols
0,100-00-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100-01-6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100-02-7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,100043-29-6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100046-00-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44450,99-98-9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
44451,9998-90-7,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0
44452,99-99-0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
44453,999-90-6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0
44454,999-97-3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0

In [8]:
import os
GroupData.to_csv(config.ROOT_DIR+'Datasets/functional_groups.csv',sep='\t')